---
- file:
  args:
    path: "{{ filebeat_path }}/{{ filebeat_program.results[0].dest | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
    state: absent
- unarchive: src={{ filebeat_program.results[0].dest }} dest={{ filebeat_path }} copy=no
- file:
  args:
    src: "{{ filebeat_path }}/{{ filebeat_program.results[0].dest | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
    path: "{{ link_path }}"
    state: link
- file:
  args:
    path: "{{ link_path }}/conf.d"
    state: directory
