---
- name: creat redis user
  user: name={{ redis_user }} append="yes" shell=/sbin/nologin createhome=no
- name: copy redis Source package
  copy: src={{ item }} dest={{ source_path }}
  with_fileglob:
  - main_program/*.tar.gz
  register: redis_program
- command: ls "{{ link_path }}"
  register: lslink
  ignore_errors: true
- import_tasks: redis_install.yml
  when: whether_repeat_install or lslink is failed
- import_tasks: redis_config.yml
