---
- name: "create pipeline dir"
  file:
    path: "{{ logstash_path }}/./pipeline"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
- name: "create settings dir"
  file:
    path: "{{ logstash_path }}/./settings"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
- name: copy logstash docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ logstash_path }}/docker-compose.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
- name: copy logstash.yml
  template:
    src: logstash.yml
    dest: "{{ logstash_path }}/./settings"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
- name: copy template logstash.conf to pipeline
  template:
    src: logstash.conf
    dest: "{{ logstash_path }}/./pipeline"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
