---
- name: create mongod_replica data directory
  file:
    path: "{{ storage_path }}/data/mongod_replica"
    recurse: yes
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
- name: Provide Replica_Set configuration files
  template:
    src: config/mongod_Replica_Set.conf
    dest: "{{ storage_path }}/mongod_replica.conf"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
- name: Provide Replica_Set startup script for linux 6
  template:
    src: init.d/mongod_replica
    dest: /etc/init.d/mongod_replica
    owner: root
    group: root
    mode: 0750
  become: true
  become_user: root
  become_method: sudo
  when: ansible_distribution_major_version == "6"
- name: Provide Replica_Set startup script for linux 7
  template:
    src: systemd/system/mongod_replica.service
    dest: /usr/lib/systemd/system/mongod_replica.service
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  become_method: sudo
  when: ansible_distribution_major_version == "7"
