---
- name: Installation dependencies mutt
  yum: name="{{ item }}" state="latest"
  with_items:
  - ncurses-devel
- name: copy mutt Source package
  copy: src={{ item }} dest={{ source_path }}
  with_fileglob:
  - main_program/*.tar.gz
  register: mutt_program
- file:
  args:
    path: "{{ source_path }}/{{ mutt_program.results[0].item | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
    state: absent
  when: whether_repeat_install
- unarchive: src={{ source_path }}/{{ mutt_program.results[0].item | basename }} dest={{ source_path }} copy=no
  register: mutt_ua_program
- name: install mutt_server
  shell: "./configure --prefix={{ mutt_path }}/{{ mutt_program.results[0].item | basename | regex_replace('^(.*).tar.gz$', '\\1') }}  && make && make install"
  args:
    chdir: "{{ source_path }}/{{ mutt_program.results[0].item | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
  when: mutt_ua_program.skipped is undefined
- file:
  args:
    src: "{{ mutt_path }}/{{ mutt_program.results[0].item | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
    path: "{{ link_path }}"
    state: link
- file:
  args:
    src: "{{ link_path }}/bin/mutt"
    path: "/usr/local/bin/mutt"
    state: link
#- shell: "ln -s {{ link_path }}/bin/* /usr/local/bin"
- name: provides mutt config
  template: src="Muttrc" dest="{{ link_path }}/etc"
