- hosts: [10.100.57.55,10.100.57.56]
  remote_user: root
  roles:
  - etcd
  vars:
    etcd_stated: install
    ETCD_VER: v3.3.10
    getfile_method: geturl
  vars_files:
  - global_vars/kubernetes.yml
# install or remove
# geturl or copyfile
