- hosts: [etcd_cluster]
  remote_user: root
  roles:
  - etcd
  vars:
    etcd_stated: install
    ETCD_VER: v3.3.10
    getfile_method: copyfile
  vars_files:
  - global_vars/kubernetes.yml
# install or remove
# geturl or copyfile
