version: '2'
services:
  kafka:
    image: {{ docker_image }}
    ports:
      - "9092:9092"
      - "{{ jmx_port }}:{{ jmx_port }}"
    environment:
      KAFKA_BROKER_ID: {{ broker_id }}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://{{ advertised_listeners }}:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: {{ zookeeper_connect }}
      KAFKA_LOG_DIRS: {{ kafka_log_dirs }}
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname={{ jmx_hostname }} -Dcom.sun.management.jmxremote.rmi.port={{ jmx_port }}"
      JMX_PORT: {{ jmx_port }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - {{ volume_log_dirs }}:{{ kafka_log_dirs }}
