---
- name: create .ssh dir
  file:
    path: "/home/{{ target_user }}/.ssh"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0700
    state: directory
- name: copy PRIVATE KEY to master node
  copy:
   src: id_rsa
   dest: "/home/{{ target_user }}/.ssh/"
   owner: "{{ target_user }}"
   group: "{{ target_user }}"
   mode: 0600
  when: ssh_keygen_private == "yes"
- copy:
   src: id_rsa.pub
   dest: "/home/{{ target_user }}/.ssh/"
   owner: "{{ target_user }}"
   group: "{{ target_user }}"
   mode: 0600
  when: ssh_keygen_private == "yes"
- name: Push authorized key
  authorized_key:
    user: "{{ target_user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - id_rsa.pub
  when: ssh_keygen_pub == "yes"
