---
- name: create .ssh dir
  file:
    path: "/root/.ssh"
    owner: root
    group: root
    mode: 0700
    state: directory
- name: copy PRIVATE KEY to master node
  copy:
   src: id_rsa
   dest: "/root/.ssh/"
   owner: root
   group: root
   mode: 0600
  when: ssh_keygen_private == "yes"
- copy:
   src: id_rsa.pub
   dest: "/root/.ssh/"
   owner: root
   group: root
   mode: 0600
  when: ssh_keygen_private == "yes"
- name: Push authorized key
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  with_file:
    - id_rsa.pub
  when: ssh_keygen_pub == "yes"
