#!/bin/bash  
# Script to fetch nginx statuses for tribily monitoring systems  
# Author: xiaoluo 
# License: GPLv2  
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:~/sbin:~/bin
source /etc/profile

Jcase=`echo $1 | tr "[A-Z]" "[a-z]"` 
_IP=$2

function active {  
/usr/bin/curl "http://$_IP/status" 2>/dev/null| grep 'Active' | awk '{print $NF}'  
}  
function reading {  
/usr/bin/curl "http://$_IP/status" 2>/dev/null| grep 'Reading' | awk '{print $2}'  
}  
function writing {  
/usr/bin/curl "http://$_IP/status" 2>/dev/null| grep 'Writing' | awk '{print $4}'  
}  
function waiting {  
/usr/bin/curl "http://$_IP/status" 2>/dev/null| grep 'Waiting' | awk '{print $6}'  
}  
function accepts {  
/usr/bin/curl "http://$_IP/status" 2>/dev/null| awk NR==3 | awk '{print $1}'  
}  
function handled {  
/usr/bin/curl "http://$_IP/status" 2>/dev/null| awk NR==3 | awk '{print $2}'  
}  
function requests {  
/usr/bin/curl "http://$_IP/status" 2>/dev/null| awk NR==3 | awk '{print $3}'  
}  
# Run the requested function  
$Jcase
