---
- file:
  args:
    path: "{{ kibana_path }}/{{ kibana_program.results[0].dest | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
    state: absent
- unarchive: src={{ kibana_program.results[0].dest }} dest={{ kibana_path }} copy=no
- file:
  args:
    src: "{{ kibana_path }}/{{ kibana_program.results[0].dest | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
    path: "{{ link_path }}"
    state: link
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
- file:
  args:
    path: "{{ kibana_path }}/{{ kibana_program.results[0].dest | basename | regex_replace('^(.*).tar.gz$', '\\1') }}"
    recurse: yes
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"

