---
- name: "create kibana dir"
  file:
    path: "{{ kibana_path }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
- name: copy kibana docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ kibana_path }}/docker-compose.yml"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
