---
- name: "creat {{ etcd_user }} user"
  user:
    name: "{{ etcd_user }}"
    comment: "etcd user"
    create_home: no
    shell: /sbin/nologin
    append: yes
- name: geturl method
  import_tasks: geturl.yml
  when: getfile_method == 'geturl'
- name: copyfile method
  import_tasks: copyfile.yml
  when: getfile_method == 'copyfile'

- file:
  args:
    path: "{{ data_path }}"
    state: directory
    owner: "{{ etcd_user }}"
    group: "{{ etcd_user }}"
    mode: 0755
- file:
  args:
    path: "{{ config_path }}"
    state: directory
- file:
  args:
    path: "{{ etcd_ssl_path }}"
    state: directory
- file:
  args:
    path: "{{ ca_ssl_path }}"
    state: directory

- name: copy ca pem
  copy:
    src: "{{ item }}"
    dest: "{{ ca_ssl_path }}"
  with_fileglob:
  - pem/ca*pem
- name: copy etcd pem
  copy:
    src: "{{ item }}"
    dest: "{{ etcd_ssl_path }}"
  with_fileglob:
  - pem/etcd*pem

- name: copy systemd file
  template:
    src: etcd.service
    dest: "/usr/lib/systemd/system"
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  become_method: sudo
- name: copy config file
  template:
    src: etcd.conf
    dest: "{{ config_path }}"
    owner: root
    group: root
  notify: Start_etcd
