---
dependencies:
  - role: edit_sudoers
    vars:
      text_var:
        - "zabbix ALL=(ALL) NOPASSWD: /usr/bin/python,/usr/bin/docker,/usr/bin/netstat"
        - "Defaults: zabbix !requiretty"
  - role: pip_depend
    vars:
      pip_var:
        - "docker"
        - "simplejson"
