---
- name: geturl method
  import_tasks: geturl.yml
  when: getfile_method == 'geturl'
- name: copyfile method
  import_tasks: copyfile.yml
  when: getfile_method == 'copyfile'

- file:
  args:
    path: "{{ flannel_ssl_path }}"
    state: directory
- file:
  args:
    path: "{{ ca_ssl_path }}"
    state: directory

- name: copy flannel pem
  copy:
    src: "{{ item }}"
    dest: "{{ flannel_ssl_path }}"
  with_fileglob:
  - pem/flanneld*pem

- name: copy ca pem
  copy:
    src: "{{ item }}"
    dest: "{{ ca_ssl_path }}"
  with_fileglob:
  - pem/ca*pem

- name: get etcd cluster Pod net INFO
  shell: "{{ etcdctl_bin }}/etcdctl --endpoints={{ ETCD_ENDPOINTS }} --ca-file={{ ca_ssl_path }}/ca.pem --cert-file={{ flannel_ssl_path }}/flanneld.pem --key-file={{ flannel_ssl_path }}/flanneld-key.pem get {{ FLANNEL_ETCD_PREFIX }}/config"
  register: flannel_podnet
  ignore_errors: true
  run_once: true
  delegate_to: "{{ delegation_etcd }}"
#- debug:
#    var: flannel_podnet

- name: set etcd cluster Pod net INFO
  shell: "{{ etcdctl_bin }}/etcdctl --endpoints={{ ETCD_ENDPOINTS }} --ca-file={{ ca_ssl_path }}/ca.pem --cert-file={{ flannel_ssl_path }}/flanneld.pem --key-file={{ flannel_ssl_path }}/flanneld-key.pem set {{ FLANNEL_ETCD_PREFIX }}/config \'{\"Network\": \"{{ CLUSTER_CIDR }}\", \"SubnetLen\": 24, \"Backend\": {\"Type\": \"vxlan\"}}\'"
  run_once: true
  delegate_to: "{{ delegation_etcd }}"
  when: flannel_podnet is failed

- name: copy systemd file
  template: src=systemd/flanneld.service dest=/usr/lib/systemd/system owner=root group=root mode=0644
  become: true
  become_user: root
  become_method: sudo
  notify: Start_flanneld
