- name: upgrade pip
  pip:
    name: "{{ item }}"
    extra_args: "--upgrade"
  loop:
    - "pip"
    - "setuptools"
- name: uninstall pip depend
  pip:
    name: "{{ item }}"
    state: absent
  loop:
    - "urllib3"
    - "chardet"
- name: install pip depend
  pip:
    name: "{{ item }}"
  loop:
    - "requests"
- name: install pip depend
  pip:
    name: "{{ item }}"
  loop: "{{ pip_var | flatten(levels=1) }}"
