---
- name: Check whether the installation of docker_compose
  command: "/usr/local/bin/docker-compose version"
  register: result
  ignore_errors: true
- import_tasks: install.yml
  when: result is failed or force_dc
