---
- name: "create data dir"
  file:
    path: "{{ elastic_path }}/{{ data_path }}"
    state: directory
    owner: "{{ elastic_user }}"
    group: "{{ elastic_user }}"
  when: data_path | dirname == '.'
- name: "create full data path"
  file:
    path: "{{ data_path }}"
    state: directory
    owner: "{{ elastic_user }}"
    group: "{{ elastic_user }}"
  when: data_path | dirname != '.'
- name: copy elastic docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ elastic_path }}/docker-compose.yml"
  when: not elastic_single
- name: copy elastic docker-compose file
  template:
    src: docker-compose-single.yml
    dest: "{{ elastic_path }}/docker-compose.yml"
  when: elastic_single
