---
- name: set PHP configuration file
  lineinfile: 
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'mysqli.default_socket ='
    line: 'mysqli.default_socket = /tmp/mysql3306.sock'
  notify:
  - start php-fpm
- lineinfile:
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'date.timezone ='
    line: 'date.timezone = Asia/Shanghai'
  notify:
  - start php-fpm
- lineinfile:
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'max_execution_time ='
    line: 'max_execution_time = 300'
  notify:
  - start php-fpm
- lineinfile:
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'memory_limit ='
    line: 'memory_limit = 128M'
  notify:
  - start php-fpm
- lineinfile:
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'post_max_size ='
    line: 'post_max_size = 16M'
  notify:
  - start php-fpm
- lineinfile:
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'upload_max_filesize ='
    line: 'upload_max_filesize = 2M'
  notify:
  - start php-fpm
- lineinfile:
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'max_input_time ='
    line: 'max_input_time = 300'
  notify:
  - start php-fpm
- lineinfile:
    dest: "{{ link_path }}/etc/php.ini"
    regexp: 'always_populate_raw_post_data ='
    line: 'always_populate_raw_post_data = -1'
  notify:
  - start php-fpm
