apiVersion: v1
kind: Pod
metadata:
  name: test-harbor-nginx6
spec:
  containers:
  - name: nginx
    image: 10.100.57.58/test/nginx:1.11.6
    ports:
    - containerPort: 80
  imagePullSecrets:
    - name: myregistrykey
