kibana_user: 1000
kibana_path: /u01/kibana
#source_path: /usr/local/src
#link_path: /usr/local/kibana
#whether_repeat_install: true

docker_image: docker.elastic.co/kibana/kibana:6.5.1

kibana_port: 5601
elasticsearch_url: http://192.168.1.193:9200
